plugins {
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

sourceSets {
    stubs {
        java.srcDir 'src/stub/java'
    }
    main {
        java.srcDir 'src/client/java'
        compileClasspath += sourceSets.stubs.output
    }
}

configurations {
    stubsImplementation.extendsFrom implementation
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

compileJava.dependsOn compileStubsJava

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.archives_base_name}" }
    }
}
